name = "einfachnurphu-io"
compatibility_date = "2025-03-25"

# Hauptausgabe f√ºr Cloudflare Pages
pages_build_output_dir = ".open-next/assets"

[build]
command = "pnpm run deploy"

[site]
bucket = ".open-next/assets"

[vars]
NODE_VERSION = "20"
