name = "einfachnurphu-io"
compatibility_date = "2024-10-01"
pages_build_output_dir = ".vercel/output/static"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm run deploy"

[build.environment_variables]
NODE_VERSION = "20"